version: "3.9"

services:
  sdx-controller:
    image: ghcr.io/atlanticwave-sdx/sdx-controller:${SDX_VERSION}
    container_name: sdx-controller
    ports:
      - "8000:8000"

  sdx-lc:
    image: ghcr.io/atlanticwave-sdx/sdx-lc:${SDX_VERSION}
    container_name: sdx-lc
    ports:
      - "8001:8001"

  kytos-sdx:
    image: ghcr.io/atlanticwave-sdx/kytos-sdx:${SDX_VERSION}
    container_name: kytos-sdx
    ports:
      - "8003:8003"

  pce:
    image: ghcr.io/atlanticwave-sdx/pce:${SDX_VERSION}
    container_name: pce
    command: ["sh", "-c", "echo 'PCE image placeholder'; sleep infinity"]

  sdx-oxp-integrator:
    image: ghcr.io/atlanticwave-sdx/sdx-oxp-integrator:${SDX_VERSION}
    container_name: sdx-oxp-integrator
    command: ["sh", "-c", "echo 'OXP Integrator placeholder'; sleep infinity"]

